disabled_rules:
  - contrasted_opening_brace
  - cyclomatic_complexity
  - file_length
  - for_where
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - line_length
  - nesting
  - opening_brace
  - optional_data_string_conversion
  - prohibited_interface_builder
  - single_test_class
  - todo
  - trailing_comma
  - type_body_length
  - type_name

opt_in_rules:
  # - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  # - empty_string
  - empty_xctest_method
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - joined_default_parameter
  - last_where
  - legacy_random
  - lower_acl_than_parent
  # - missing_docs
  - modifier_order
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_interface_builder
  - prohibited_super_call
  - reduce_boolean
  - reduce_into
  - redundant_type_annotation
  - self_binding
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - superfluous_disable_command
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - xct_specific_matcher

blanket_disable_command:
  allowed_rules:
    - missing_docs

excluded:
  - .build
  - Scripts
